### ISSUE TITLE
Spurious "never modified and could have been declared const or immutable"

### ISSUE THREAD

**Issue by mark-summerfield** [dlang-community/D-Scanner#793] opened 2020-02-23 12:27 UTC
I have these lines of GtkD code:
```d
        uint kv;
        event.getKeyval(kv); // ref arg is updated here
```
but `dscanner --syntaxCheck` gives me this warning:
`Variable kv is never modified and could have been declared const or immutable.`

But the warning is invalid since `kv` is (or could be) changed by the call since the callee's signature is `bool getKeyval(out uint keyval)`; see https://api.gtkd.org/gdk.Event.Event.getKeyval.html

There are a few GtkD functions I've encountered with these kinds of signature, so it would be nice if dscanner could spot them.

**Comment by WebFreak001** [comment] 2020-02-24 07:58
duplicate of #366

**Closed by WebFreak001** 2020-02-24 07:58 UTC
