### ISSUE TITLE
Remove DMD-nightly from Travis.

### ISSUE THREAD

**Issue by skl131313** [dlang-community/D-Scanner#456] opened 2017-06-13 13:28 UTC
It's too unstable, features/bugs get introduced and removed/fixed too regularly. Which is why I didn't include it at first. Whether the build is successful or not depends entirely on an uncontrollable external source.

Thoughts?

**Comment by BBasile** [comment] 2017-06-13 13:34
I don't know, on one hand today we have discovered a problem on emsi containers thanks to that, on the other regressions discovering is more the job of https://github.com/dlang/ci (where D-Scanner could be added perhaps ?)

**Comment by wilzbach** [comment] 2017-06-13 15:13
Yes imho it shouldn't be that unstable! And only if people test it, regressions can be prevented.
That being said a lot less should break if Dscanner is part of the project tester (note that libdparse and EMSI containers are already on the list, EMSI is just disabled at the moment). Also the project tester is still in alpha mode and currently not required to pass for PRs at DMD and Phobos, but it soon will be (i.e. once the current regressions have been fixed, it's passing state will be required).

FWIW Martin is very happy to extend the reach of the project tester, just today I made a PR to add D-YAML:

https://github.com/dlang/ci/pull/42

(It's already has already been merged)

**Comment by skl131313** [comment] 2017-06-14 18:26
Alright seems as though it is useful, maybe if there's a way to change it so it is more of a 'warning' than an error if it doesn't build. Don't know if that is possible though.

**Comment by BBasile** [comment] 2017-06-15 11:03
The only way i see here is to have two test matrices:
- stable (dmd / ldc).
- upstream compiler: nightly / beta version of the compilers.

Because, once again, now we have a red badge on the README while the product builds fine.
I hate this situation !

**Comment by wilzbach** [comment] 2017-06-15 14:55
> Because, once again, now we have a red badge on the README while the product builds fine.
> I hate this situation !

An idea:

https://github.com/dlang-community/D-Scanner/pull/459

**Comment by wilzbach** [comment] 2017-06-17 10:21
FYI the critical PR has been reverted and the reduced regressions have been added to the test suite: 

https://github.com/dlang/dmd/pull/6913

**Comment by ZombineDev** [comment] 2017-06-18 12:25
Closing as "never fix". See also https://github.com/dlang/dmd/pull/6913#issuecomment-309213747.

The almost inevitable (in the short term at least) problems arising from testing dmd-nightly are miniscule compared to the enormous benefit of stopping a regression from reaching the official dmd release. We as community play a large part in making D better with every release for everyone.
This is not just some personal project where the author can come cry on forums that latest release broke his project, without bothering to test the compiler before its release, with all this great CI infrastructure available for free. After all, almost all D IDEs/text editor plugins depend in some way on these projects, making their stability (which depend on dmd's stability) critical for D's success.

**Closed by ZombineDev** 2017-06-18 12:25 UTC

**Comment by skl131313** [comment] 2017-06-18 13:52
@ZombineDev

It should be something that DMD tests instead if it is that important. Using CI for this project is useful in making sure it works and any changes that are made work as well. That becomes a bit less useful when every second day there's a build failure because it is testing a build against a very experimental compiler. It tests dmd-beta which does essentially the same thing, though not as quickly but at less of the expense of this project.

https://github.com/dlang-community/D-Scanner/pull/459

Workarounds like these shouldn't have to be implemented for a compiler that gets a new version every night.
